12-food-distribution
codeuniversity/al-cis pull request #10
Opened 2019-02-27 19:05 UTC by Urhengulas

https://trello.com/c/fx2RxXOz/12-food-distribution

 - 4-dim mechanical wave function

2019-02-27 19:06 UTC, Urhengulas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Food distribution](https://trello.com/c/fx2RxXOz/12-food-distribution)

2019-02-27 19:13 UTC, elli-wolf requested changes
https://github.com/codeuniversity/al-cis/blob/479cc7f1db9f6c72883eaa5f638426e163e843a3/food.py#L18-L22
This loop could be in `cell_computing_service` to enhance the readability of the `cell_computing_service`.

2019-02-27 19:13 UTC, Animuslupus commented on food.py
> +def alive(cell):
`is_alive` is already implemented in cis_cell.py, maybe you should import it

2019-02-27 19:27 UTC, elli-wolf requested changes
You should maybe think about, replacing the function generators with actual functions. Since you don't gain any benefit through the use of function generators.

2019-02-27 19:31 UTC, elli-wolf requested changes
I think it would be useful if you would integrate these changes into `cis_env`.

2019-03-04 11:33 UTC, alexmorten commented on cell_computing_service.py
> +
FYI: After feeding all the cells, it is probably a good idea to still average the energy level inside a connected cell group with `average_out_energy_in_connected_cells` (you removed that call in the merge)

2019-03-04 12:50 UTC, Animuslupus commented on cis_env.py
> +def normalize(num, definition_area_size=6):
The function name `normalize` is too brought, normalization can reference to wide range of procedures and processes, it isn't clear which one of them you reference.

2019-03-04 12:51 UTC, Animuslupus commented on cis_env.py
> +        Normalizes the defenition area of the num to {0, 1} .
There is a spelling mistake in definition :sweat_smile:

2019-03-04 12:55 UTC, elli-wolf requested changes

2019-03-04 12:55 UTC, Animuslupus commented on cis_env.py
> +import scipy.constants as cons
If you want to use scipy in CIS you have to add it to the dependencies. But maybe you also find a more elegant way to import the speed of light :wink:.

2019-03-06 12:39 UTC, merged